var num = [1, 2, 3, 4];
num.at(1)
num.push(5)
num.pop()
num.fill(1)
num.shift()
num.unshift(5)
num.reverse()
num.includes(2)
num.map(item => item * 2)
num.filter(item => item > 2)
num.find(item => item > 2)
num.findIndex(item => item === 2)
num.every(item => item > 0)
num.reduce((acc, item) => acc + item, 0)
num.toString()
num.join('*')
num.splice(1, 2, 'h', 'm')
num.slice(1, 3)
num.sort()
x.sort(function(a, b){return a - b})
x.sort(function(a, b){return b - a})
x.sort(function(a, b){return 0.5 - Math.random()})